#! /bin/sh
### BEGIN INIT INFO
# Provides:          Autostart cameradatenlogger
# Required-Start:    -
# Required-Stop:     -
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops My Programm
# Description:       Starts & Stops My Programm
### END INIT INFO
 
#Switch case fuer den ersten Parameter
case "$1" in
    start)
    #Aktion wenn start uebergeben wird
        echo "Starte CameraDatenlogger"
    /home/pi/Desktop/CameraDatenLogger/autostart.py
        ;;
 
    stop)
    #Aktion wenn stop uebergeben wird
        echo "stop nothing"
        ;;
 
    restart)
    #Aktion wenn restart uebergeben wird
        echo "Restarte nothing"
        ;;
 *)
 #Standard Aktion wenn start|stop|restart nicht passen
 echo "(start|stop|restart)"
 ;;
esac
 
exit 0
